### ISSUE TITLE
Error on Reactions

### ISSUE THREAD

**Issue by DWD420** [fraserdale/freeCarts#35]
![image](https://user-images.githubusercontent.com/39104395/54884958-d8ab8800-4e6e-11e9-80aa-1801f22ea398.png)

Get these two errors when a reaction is added to a cart - Have you come across this in testing?

**Comment by simon-kim** [comment]
I'm also getting this. When a user is using Latchkey,
`reaction.message.embeds[0].footer.text` is 'Latchkey Bot IO'

So when you try to do this `cartID = (reaction.message.embeds[0].footer.text).split('# ')[1].split(' • M')[0]`,
the [1] is undefined because there is no # found in the string.

Haven't really debugged further than that.

**Comment by simon-kim** [comment]
@fraserdale

**Comment by jamesbao1208** [comment]
pls need help this error, i can pay money for this

**Comment by connorlurring** [comment]
@simon-kim so is the cart ID after the `#` in the message `undefined`?

I will update LatchKey support to reflect this if so.
